### ISSUE TITLE
redis.exceptions.DataError: Invalid input of type: 'UUID'

### ISSUE THREAD

**Issue by Nuqlear** [vaidik/sherlock#32]
environment:
- Python 3.6
- sherlock==0.3.1
- redis>=2.10.6

traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/search/src/search_service/tasks/common.py", line 29, in queue
    with RedisLock("(queue/wipe)lock", client=self.app.redis_client):
  File "/usr/local/lib/python3.6/site-packages/sherlock/lock.py", line 199, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.6/site-packages/sherlock/lock.py", line 171, in acquire
    if self._acquire() is not True:
  File "/usr/local/lib/python3.6/site-packages/sherlock/lock.py", line 429, in _acquire
    expire]) != 1:
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3498, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2704, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'UUID'. Convert to a byte, string or number first.
```

It seems that sherlock has tests for Python 3 and they are passing... Why I am getting the exception then?

**Comment by vaidik** [comment]
Apologies for not being able to respond to this earlier. I have fixed the issue. And will make a release soon.

**Comment by tesserakt** [comment]
This seems to still be an issue, even on 0.3.2

**Comment by shaleh** [comment]
Confirmed. I am also seeing this with Sherlock 0.3.2 and Python 3.6.

```
File "/usr/local/lib/python3.6/site-packages/sherlock/lock.py", line 171, in acquire
    if self._acquire() is not True:
  File "/usr/local/lib/python3.6/site-packages/sherlock/lock.py", line 429, in _acquire
    expire]) != 1:
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3575, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2761, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 663, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 125, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'UUID'. Convert to a byte, string or number first.
```
